---
- hosts: all
  user: ec2-user
  sudo: True

  vars_files:
   - vars/hidden.yml

  tasks:
  - include: tasks/freenx-install.yml

  - include: tasks/freenx-setup.yml

  - include: tasks/copy-nx-node-config.yml

  - include: tasks/useradd-user.yml

  - include: tasks/copy-sshd-config.yml

  handlers:
  - include: handlers/handlers.yml
